import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { ThemeProvider } from "@/providers/theme-provider";
import { Toaster } from "@/components/ui/sonner";
import { ModalProvider } from "@/providers/modal-provider";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  console.log('in the layout of the layout fsttu')

  return (
    // Use of suppressHydrationWarning is due to the ThemeProvider
    // causing a hydration error when server side rendering
    <html lang="en" suppressHydrationWarning>
      <body className={`${inter.className} dark:bg-slate-900`}>
      <ModalProvider />
      <ThemeProvider
          attribute="class"
          defaultTheme="dark"
          enableSystem
          disableTransitionOnChange
        >
          {children}
        </ThemeProvider>

        <Toaster />      
      </body>
    </html>
  );
}
