services:

    database:
        image: arm64v8/postgres:16.2
        # image: postgres:13
        restart: unless-stopped
        volumes:
            - repetition:/var/lib/postgresql/data:delegated
        ports:
            - "5432:5432"
        environment:
          - POSTGRES_DB=repetition
          - POSTGRES_USER=admin
          - POSTGRES_PASSWORD=repetition

# using this named volume ensures db's hang around between launches 
volumes:
    repetition:


